### ISSUE TITLE
Differences in mesh color when using drainColor

### ISSUE THREAD

**Issue by joshmao** [diarmidmackenzie/instanced-mesh#34]
Hi Diarmid,

Been loving this component, super useful and convenient to use, thank you for creating it! 

I noticed a small discrepancy in my mesh colors when using the `drainColor` property and was wondering if there was a bug in the component? I am using A-Frame `v.1.4.1`.

The image below shows 2 `a-boxes` colored with the same hex value `#8DA34E`, the higher one is a non-instanced mesh while the lower one is an instanced-mesh with `drainColor:true` and the color is set through the `colors` property. You can see the instanced-mesh cube is much lighter than the regular one,  I wonder if the base white color is bleeding through or if I'm doing something wrong in the implementation?

![instacedmeshcomparison](https://github.com/diarmidmackenzie/instanced-mesh/assets/61892233/c0438d5e-9c11-402d-913b-26ec9c7ffc2c)

relevant code:
```
<a-box id="mesh2" color="#8DA34E" position="0 4 -2"> </a-box>

<a-box id="mesh1" color="#456C22" instanced-mesh="drainColor:true;"> </a-box>
<a-entity id="block1" position="-2 2 -2" instanced-mesh-member="mesh:#mesh1; colors:#8DA34E;">
</a-entity>
```

**Comment by diarmidmackenzie** [comment]
Hi, can you check what version you are using?

drainColors is only implemented in v0.7.0, and I just noticed the README still refers to 0.6.0.  Might you be using an old version?

**Comment by diarmidmackenzie** [comment]
Using the 0.7.0 version, and your code fragment, the colors in this glitch look good to me:

https://glitch.com/edit/#!/scalloped-berry-smoke?path=index.html%3A8%3A35

![image](https://github.com/diarmidmackenzie/instanced-mesh/assets/16045703/dd5f381b-742c-4713-9af4-4abbe350372a)

**Comment by joshmao** [comment]
hi @diarmidmackenzie thanks for testing. I took a look at my code and I am using `v0.7.0`; I did some further testing and found out that the color variation is due to the [colorManagement](https://aframe.io/docs/1.4.0/components/renderer.html#properties_colormanagement) property of the `renderer` AFrame parameter attached to my `<a-scene>`.

In the photo below, you can see that the colors render correctly when `renderer="colorManagement: false"` but is varied when `renderer="colorManagement: true"`. I use `colorManagement` often as it helps to accurately render the color of 3D models in A-Frame and I was wondering if you knew why this could be happening/if there's a workaround.

![colormanagement](https://github.com/diarmidmackenzie/instanced-mesh/assets/61892233/24c68c2a-f733-47bd-9e9a-f15c9651cb27)

**Comment by diarmidmackenzie** [comment]
Interesting.  I will look into this some more.

**Comment by diarmidmackenzie** [comment]
So we have a simple repro with A-Frame 1.4.2 here:
https://glitch.com/edit/#!/scalloped-berry-smoke?path=index.html%3A12%3A26

![image](https://github.com/diarmidmackenzie/instanced-mesh/assets/16045703/188260e2-5f64-475f-99d3-f02d130f4fc8)


Here's an equivalent with pure THREE.js, and the same renderer settings that are applied when colorManagement is enabled...
https://glitch.com/edit/#!/alluring-dent-gambler?path=index.html%3A33%3A21

What's odd here is that *both* cubes end up the lighter color.

I found this PR, which seems relevant.
https://github.com/aframevr/aframe/pull/5210

So it appears that in A-Frame 1.4.2 (prior to this PR), when colorManagement is used, hex colors need to be adjusted using `applyColorCorrection(colorOrTexture)`.  This component doesn't do that, so I guess that's the bug.

From A-Frame 1.5.0 it seems that this should not longer be necessary.

Fix looks fairly straightforward.

**Comment by diarmidmackenzie** [comment]
This version of instanced mesh fixes the problem.

https://cdn.jsdelivr.net/gh/diarmidmackenzie/instanced-mesh@acdc085/src/instanced-mesh.min.js

**Comment by joshmao** [comment]
thanks for investigating and the quick fix @diarmidmackenzie! I really appreciate it.
