### ISSUE TITLE
Positioning of children not working as expected

### ISSUE THREAD

**Issue by diarmidmackenzie** [diarmidmackenzie/instanced-mesh#4]
Query:

Positioning of children beneath the parent entity does not work as expected. (For example a parent entity with position="0 30 -60" doesn't seem to move the children instanced mesh entities by the same amount as I would expect normally.) Is this the same issue as "Diverse Frames of Reference" mentioned in the readme? Regarding the performance consideration, maybe it'd be possible to allow initial setting of the position but then not after that for children unless explicitly requested?

**Comment by diarmidmackenzie** [comment]
The documentation on "frames of reference", the documentation isn't very clear - sorry!

Basically the code just naively takes the localMatrix (i.e. position, orientation, scale) for the member's object3D and adds an entry for this position matrix in the instanced mesh array of positions, without any adjustments.

That means that
- If the instanced mesh and the child objects have the same parents in the scene graph, everything should work just fine.
- If the instanced mesh and the member object are at different positions in the scene graph, all bets are off, since the localMatrix of the member won't have the expected meaning in the context of the instanced mesh.

I'd be up for fixing this.  It's pretty straightforward to transform a localMatrix into a different frame of reference.  The concern is what happens when the scene graph above the members, or above the instanced mesh, gets modified subsequently.

I think it would be OK to start off with a naive implementation where things only "catch up" on explicit updates to the member.  Sounds like that would meet your needs, and it's a net improvement on what we have today.  I think I'll do that for now, and then if it proves that more flexibility is needed, I can go ahead and do that.

**Comment by diarmidmackenzie** [comment]
I've made some changes which should support this:
https://github.com/diarmidmackenzie/instanced-mesh/commit/ec92cc6b3137f086bd2207349f4410bd510877f0

Tested with some static examples here: https://github.com/diarmidmackenzie/instanced-mesh/blob/main/tests/positioning.html

Waiting for some positive feedback on this before cutting a new release.

**Comment by diarmidmackenzie** [comment]
Just to be clear, you need to set "positioning: world" on the instanced mesh to enable the new function.

**Comment by kfarr** [comment]
Yes the new version works as expected when "positioning: world" is used: https://aframe-instanced-mesh-building-test.glitch.me/

**Comment by diarmidmackenzie** [comment]
I've now published v0.4.0 with this fix included.
