### ISSUE TITLE
GLTF models with multiple meshes

### ISSUE THREAD

**Issue by diarmidmackenzie** [diarmidmackenzie/instanced-mesh#5]
Query: 

I have a GLTF file with 3 meshes under a node.  When used with instanced-mesh it only shows 1 of the 3 meshes.

**Comment by diarmidmackenzie** [comment]
For GLTF models with more than one mesh (which I'd not given any consideration up until now), the code will just take the first mesh that it finds, extract the geometry and all the materials from that mesh, and use these for the instanced mesh.

My understanding is that a single Instanced Mesh can only have a single geometry.

So to support GLTF models with multiple meshes/geometries, we'd only have 2 options:
 A - Create multiple Instanced Meshes, one for each mesh/geometry in the GLTF model.
 B - Merge the geometries in the GLTF model into a single geometry.

Both solutions have moderate complexity.  B involves more unknowns for me (I haven't really looked at merging geometries yet), but seems more elegant, and would probably give better performance (fewer draw calls).

The other option, is to update the GLTF model so that the geometries are already merged into a single geometry in each GLTF model.

Seems like pre-merging within the GLTF model will give the best performance, so seems like that might be the best solution to me.  But if there are a lot of models like this, and it's a lot of manual work to fix them up, I can see you might prefer either A or B above.

Are there specific reasons to have multiple meshes within a GLTF model?  Or is it just a case of these being the assets that you have, and it's a bunch of work to change them?  If the latter, is it a moderate amount of work, or a lot of work?

I'm happy to look further at this, but not immediately keen to jump on it and implement a fix, as I don't yet understand what the benefits would be of having multiple meshes within a GLTF model, rather than a single mesh...

**Comment by diarmidmackenzie** [comment]
I have had a go at solution A.  In new "multi-mesh" branch.

https://github.com/diarmidmackenzie/instanced-mesh/tree/multi-mesh

Turned out to be a bit more complicated than I had thought as I also needed to allow for the fact that sub-meshes can each have different transform matrices within the model, and you need to account for the full hierarchy of transform matrices, not just the local matrix of the mesh itself...

But I seem to have this working now,  See: tests/3d-models-multi-mesh.html

Interestingly, these changes have slightly affected my other GLTF tests: tests/3d-models.htm.  All helmets have been rotated by 90 degrees.

I think that's actually fixed vs. previous code.  The 90 degree rotation was higher up in the GLTF object hierarchy, so the previous code didn't take it into account, and I didn't notice the issue and just compensated for it in my test script...  The new code accounts for that rotation, and so we end up with more correct behaviour.

I'm expecting to bring this into main eventually, but want to do a bit of tidy & testing first.  In the meantime I wanted to make this available to anyone who might be interested.

**Comment by diarmidmackenzie** [comment]
@kfarr - you might be interested in this.  Please let me know if you have any feedback.

There's a lot of potential for complexity in the GTLF model hierarchies so if you have a particular model it doesn't work with, I'd be happy to take a look.

**Comment by diarmidmackenzie** [comment]
Other note: further research led me to the conclusion that doing B at runtime was not feasible, e.g. https://discourse.threejs.org/t/is-it-possible-to-instance-a-complete-gltf-that-is-imported-to-three-js/8894

Pre-processing the models into a single mesh is of course possible (though I don't know what the best tools are for this).  But trying to do that at runtime seems like a bad option to me.

Reason I went ahead to implement this, even though in general pre-processing to a single mesh is better, is that I think this will still be valuable to some folks who want to be able to use standard GLTF models out of the box without having to develop a complex pre-processing pipeline.

**Comment by donmccurdy** [comment]
Seems like you've already come to this conclusion, but just want to add a +1 for (A) as the right approach here. 

Pre-processing to merge models is a good idea — gltfpack does this, for example — but even a good pre-processor can't merge everything. For example, transparent and opaque meshes should not be merged. So being able to do (A) and create multiple InstancedMesh objects is still necessary even if you were to implement (B) as well.

Aside, gltfpack's output would be a good source of test cases here. With default settings it will merge and quantize geometry, adding scaling factors to nodes throughout the scene that would require you to consider the world transform for each object. This can be disabled with the `-noq` option, which will just merge things without quantizing or rescaling. The final scene bounding box should be the same with either option. Examples:

[Archive.zip](https://github.com/diarmidmackenzie/instanced-mesh/files/7023465/Archive.zip)

**Comment by diarmidmackenzie** [comment]
v0.5.0 now released with option A implemented.
