### ISSUE TITLE
Flat shading with custom texture

### ISSUE THREAD

**Issue by aframenerd** [diarmidmackenzie/instanced-mesh#7]
Hello Diarmid, 
Thank you so much for this great addition to A-frame. Resolving draw calls adds so many possibilities to what we can create.

However, it seems using custom textures and normal maps on a mesh first up just doesn't work, and if you force it through a component with Three.js's API, it breaks the lighting of the mesh and becomes flat shaded.

Is this something inherent to the way the instancing component works and is hard to fix or am I just doing something silly? It would mean the world to me if it could work with normal maps. I can provide example code, or anything else you might need help with.

All the best

**Comment by diarmidmackenzie** [comment]
Hi - very happy to look at this.

If you can provide a sample of a mesh that has the problem - e.g. on glitch - that would be a good place to start from.

**Comment by diarmidmackenzie** [comment]
Not to worry, I have created a basic example that's showing a clear problem.

https://diarmidmackenzie.github.io/instanced-mesh/tests/texture-example.html

From a very quick look, it looks like the textures aren't yet set up at the point we clone the texture for the instanced mesh, so they get lost.  Hopefully won't be too hard to fix up to handle this - hope to get to this tomorrow...

**Comment by diarmidmackenzie** [comment]
I have made a fix that makes that basic textures example work:

https://github.com/diarmidmackenzie/instanced-mesh/commit/a26802dd419a39fd0680fba4fb8ae7c2247a768f

Fix is to wait for textures to load before cloning material for the instanced mesh.

Now working here:
https://diarmidmackenzie.github.io/instanced-mesh/tests/texture-example.html

I will add some more tests tomorrow to specifically cover:
- meshes with multiple texture maps (I expect this to work, but need to check).
- a wider range of uses of textures (env-maps, normals, displacement etc.) (shouldn't be any differences, but again I'd like to check).

If you have any feedback on this in the meantime, please do let me know.

**Comment by diarmidmackenzie** [comment]
OK - there were a few more changes needed to get envMaps & Normal/Disp./AmbientOcc maps working.

New (now working) examples here:
https://diarmidmackenzie.github.io/instanced-mesh/tests/pbr-example.html
https://diarmidmackenzie.github.io/instanced-mesh/tests/env-map-example.html

**Comment by aframenerd** [comment]
Great Scott!! Incredible work, Diarmid.
It's people like you that keep the open source spirit alive.

**Comment by diarmidmackenzie** [comment]
Happy to help.  And thanks for your kind words.

I would love to see what you do with this :-)
